# This contains only properties different from application.properties
# this is for connectiong to the dhinfra server over PtP OpenVPN  
target.host=https://78.104.159.78:3030
# This is necessary for HTTPS with self signed certs
# the file keystore.p12 must exist in resources (backend/src/main/resources/keystore)
trust.store=classpath:keystore/keystore.p12
trust.store.password=password
